### ISSUE TITLE
Twitter Link in Pol Detail View Brings Up Empty Modal

### ISSUE THREAD

**Issue by ianagne** [gabivoicu/Accountabill#106]
Need to correct twitter link to either direct to a politician's twitter page or bring up a modal to tweet at the politician.

**Comment by gabivoicu** [comment]
can we implement the modal? how far away from succeeding were we last week?

**Comment by ianagne** [comment]
From what I understand, we need to do four things:
1) Create a if/else to send the user to twitter sign-in when they click on the link when there is no current user, and send the user to the modal when there is a current user.
2) Populate the modal with a form that sends a tweet through #create in the tweet controller
3) Style everything with beautiful
4) Implement a character counter and error messaging for failed tweets

**Comment by gabivoicu** [comment]
Closing this so it no longer shows up in my Trailer notifications. Accountabill forever ✌🏻
