### ISSUE TITLE
Tooltip disappears

### ISSUE THREAD

**Issue by gabivoicu** [gabivoicu/Accountabill#110]
Tooltip disappears on Chrome & Safari on iMac behind nav bar. Even when reducing browser window size to be smaller than laptop (as no issue appears on laptop), tooltip disappears. No flashing at least.
![screen shot 2015-03-22 at 12 23 25 pm](https://cloud.githubusercontent.com/assets/8533377/6770477/eca263a4-d08e-11e4-8d03-71995f5882ae.png)

**Comment by gabivoicu** [comment]
This happens for all of the different D3 charts.

Update: flashing still happens on donut charts.

**Comment by ianagne** [comment]
I'm strongly considering converting all d3 charts to [Hightcharts](http://www.highcharts.com/demo) for ease of use.

**Comment by gabivoicu** [comment]
@ianagne Do it! I'd love to see what it looks like. We can keep both D3 and Highcharts on separate branches. We can have a `master-d3` and `master-highcharts`.

**Comment by gabivoicu** [comment]
Closing this so it no longer shows up in my Trailer notifications. Accountabill forever ✌🏻
